name: Testing

on:
  push:
    branches:
      - main
      - dev-2.0
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            browser: chrome
            test-workspace: unit-tests-chrome
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Chrome with SwiftShader
        run: |
          sudo apt-get update
          curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o chrome.deb
          sudo apt-get install -y ./chrome.deb
          ls -R /opt/google/chrome/swiftshader
      
      - name: Verify Chrome (Ubuntu)
        if: matrix.os == 'ubuntu-latest' && matrix.browser == 'chrome'
        run: |
          google-chrome --version
      
      - name: Get node modules
        run: npm ci
        env:
          CI: true
      
      - name: Build and test (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: npm test -- --project=${{ matrix.test-workspace }}
        env:
          CI: true
      
      - name: Report test coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
        env:
          CI: true
