name: Testing

on:
  push:
    branches:
      - main
      - dev-2.0
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            browser: chrome
          - platform: self-hosted
            browser: chrome

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Verify Chrome (Ubuntu)
        if: matrix.platform == 'ubuntu-latest' && matrix.browser == 'chrome'
        run: |
          google-chrome --version

      - name: Verify Chrome (Windows)
        if: matrix.platform == 'windows-latest' && matrix.browser == 'chrome'
        run: |
          & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version
      
      - name: Get node modules
        run: npm ci
        env:
          CI: true

      - name: Build and test WebGPU (Ubuntu)
        if: matrix.platform == 'self-hosted'
        run: |
          Xvfb :99 -screen 0 1280x720x24 &
          export DISPLAY=:99
          npm test -- --project=unit-tests-webgpu
        env:
          CI: true

      - name: Build and test (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: npm test -- --project=unit-tests
        env:
          CI: true

      - name: Report test coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
        env:
          CI: true
